import dbop, config

shortcuts = ["LLV"]

def update_latest():
    global people,places
    
    people = dbop.get_database(config.PEOPLE_DB)
    places = dbop.get_database(config.PLACES_DB)    

people = dbop.get_database(config.PEOPLE_DB)
places = dbop.get_database(config.PLACES_DB)

capital_people={"tin", "tung", "hoa", "zu", "an", "trang"}


normalize_language_with_accent_mark = {
    "bùn": "buồn",
    "đãk": "đã",
    "qá": "quá",
    "zữ": "dữ",
    "zũ": "vũ",
    "zãi": "vãi",
    "típ": "tiếp",
    "hỉu": "hiểu",
    "cừi": "cười",
    "cúi": "cuối",
    "mụt": "một",
    "nhìu": "nhiều",
    "nhiu": "nhiêu",
    "qá": "quá",
    "xún": "xuống",
    "lừi": "lười",
    "chiện": "chuyện",
    "gòi": "rồi",
    "gữi": "rưỡi",
    "lứt": "lướt",
    "pạn": "bạn",
    "pán": "bán",
    "pắn": "bắn",
    "pàn": "bàn",
    "zẫn": "vẫn",
    "củm": "cảm",
    "ló": "nó",
    "lúm": "lắm",
    "chìu": "chiều",
    "xợ": "sợ",
    "bụn": "bụng",
    "tìn": "tiền",
    "qên": "quên",
    "ngụ": "ngủ",
    "đọ": "đó",
    "dứi": "dưới",
    "nớp": "lớp",
    "nụa": "nữa",
    "gùi": "rồi",
    "kím": "kiếm",
    "gớt": "rớt",
    "đth": "điện thoại",
    "kỉu": "kiểu", 
    "đòu": "đầu",
    "trứ": "chứ",
    "đắc": "đất",
    "tón": "toán",
    "gất": "rất",
    "zà": "và",
    "đựt": "được",
    "phưm": "phim",
    "zòng": 'vòng',
    "ngừi": "người",
    "zì": "gì",
    "zị": "vị",
    "mắ": "má",
    "a": "anh",
    "đ": "không",
}

normalize_language_no_accent_mark = {
    "ac": "acc",
    "ak": "ác",
    "ang": "ăn",
    "bt": "bài tập",
    "byt": "buýt",
    "bic": "biết",
    "biec": "biết",
    "chs": "chơi",
    "coa": "có",
    "cgi": "cái gì",
    "ctrinh": "chương trình",
    "cnhat": "chủ nhật",
    "ch": "chưa",
    "chug": "chung",
    "cum": "cũng",
    "cụa": "của",
    "cko": "cho",
    "ckac": "chắc",
    "dc": "được",
    "dr": "đúng rồi",
    "droi": "đúng rồi",
    "dou": "đâu",
    "dg": 'đang',
    "dl": "deadline",
    "dko": "đúng không",
    "dk": "đúng không",
    "ei": "ê",
    "ga": "ra",
    "gut": "rút",
    "gke": "ghê",
    "got": "rot",
    "h": "giờ",
    "hog": "không",
    "hok": "học",
    "hec": "hết",
    "hme": "hề",
    "iu": "yêu",
    "koi": "coi",
    "kiu": "kêu",
    "ktra": "kiểm tra",
    "khok": "khóc",
    "loi": "nói",
    "lun": "luôn",
    "liu": "liệu",
    "lay": "nay",
    "ms": "mới",
    "mng": "mọi người",
    "mec": "mệt",
    "mun": "muon",
    "min": "mình",
    "ng": "người",
    "nc": "nước",
    "nchien": "nói chuyện",
    "ngc": "ngược",
    "nka": "nha",
    "ngol": "ngon",
    "nhma": "nhưng mà",
    "nhao": "nhau",
    "nki": "nhật kí",
    "pay": "bay",
    "pa": "ba",
    "pan": "ban",
    "khom": "không",
    "ko": "không",
    "kon": "con",
    "ktay": "khoai tây",
    "qa": "qua",
    "qen": "quen",
    "qan": "quan",
    "qay": "quay",
    "qai": "quai",
    "qcao": "quảng cáo",
    "quánh": "đánh",
    "r": "rồi",
    "sn": "sinh nhật",
    "sou": "sầu",
    "siu": "siêu",
    "shai": "sai",
    "thiec": "thiệt",
    "trc": "trước",
    "thg": "thang",
    "tar": "ta",
    "tr": "trời",
    "tiu": "tiêu",
    "thoy": "thôi",
    "tnhan": "tin nhắn",
    "th": "thôi",
    "un": "uống",
    "xog": "xong",
    "xao": "sao",
    "ze": "ve",
    "zu": "du",
    "zo": "vô",
    "ziet": "viet",
    "zoi": "với",
    "z": "vậy",
    "zui": "vui",
    "zay": "vậy",
    "zua": "vua",
}