shortcuts = ["LLV"]

people = {"ktay","tay", "rot", "vu", "ti na", "thi'm", "khang", "qe nhe", "kim qag", "kim hon", "bich thot", "thuy trang", "btran", "chi heo", "trihao", "an", "mr"}

normalize_language_with_accent_mark = {
    "bùn": "buồn",
    "đãk": "đã",
    "qá": "quá",
    "zữ": "dữ",
    "zũ": "vũ",
    "zãi": "vãi",
    "típ": "tiếp",
    "hỉu": "hiểu",
    "cừi": "cười",
    "cúi": "cuối",
    "mụt": "một",
    "nhìu": "nhiều",
    "nhiu": "nhiêu",
    "qá": "quá",
    "xún": "xuống",
    "lừi": "lười",
    "chiện": "chuyện",
    "gòi": "rồi",
    "gữi": "rưỡi",
    "lứt": "lướt",
    "pạn": "bạn",
    "pán": "bán",
    "pắn": "bắn",
    "pàn": "bàn",
    "zẫn": "vẫn",
    "củm": "cảm",
    "ló": "nó",
    "lúm": "lắm",
    "chìu": "chiều",
    "xợ": "sợ",
    "bụn": "bụng",
    "tìn": "tiền",
    "qên": "quên",
    "ngụ": "ngủ",
    "đọ": "đó",
    "dứi": "dưới",
    "nớp": "lớp",
    "nụa": "nữa",
    "gùi": "rồi",
    "kím": "kiếm",
    "gớt": "rớt",
    "đth": "điện thoại",
    "kỉu": "kiểu", 
    "đòu": "đầu",
    "trứ": "chứ",
    "đắc": "đất",
    "tón": "toán",
}

normalize_language_no_accent_mark = {
    "ac": "acc",
    "ang": "ăn",
    "bt": "bài tập",
    "byt": "buýt",
    "bic": "biết",
    "biec": "biết",
    "chs": "chơi",
    "coa": "có",
    "cgi": "cái gì",
    "cnhat": "chủ nhật",
    "ch": "chưa",
    "chug": "chung",
    "cum": "cũng",
    "cko": "cho",
    "ckac": "chắc",
    "dc": "được",
    "dr": "đúng rồi",
    "droi": "đúng rồi",
    "ei": "ê",
    "ga": "ra",
    "goi": "roi",
    "gut": "rút",
    "gke": "ghê",
    "got": "rot",
    "h": "giờ",
    "hog": "không",
    "hok": "học",
    "hec": "hết",
    "hme": "hề",
    "koi": "coi",
    "kiu": "kêu",
    "ktra": "kiểm tra",
    "loi": "nói",
    "lun": "luôn",
    "liu": "liệu",
    "lay": "nay",
    "ms": "mới",
    "mng": "mọi người",
    "mec": "mệt",
    "min": "mình",
    "ng": "người",
    "nc": "nước",
    "ngc": "ngược",
    "nka": "nha",
    "nhma": "nhưng mà",
    "nhao": "nhau",
    "pay": "bay",
    "pa": "ba",
    "pan": "ban",
    "khom": "không",
    "ko": "không",
    "kon": "con",
    "ktay": "khoai tây",
    "qa": "qua",
    "qen": "quen",
    "qan": "quan",
    "qcao": "quảng cáo",
    "quánh": "đánh",
    "sn": "sinh nhật",
    "sou": "sầu",
    "shai": "sai",
    "thiec": "thiệt",
    "trc": "trước",
    "thg": "thang",
    "tar": "ta",
    "tr": "trời",
    "thoy": "thôi",
    "tnhan": "tin nhắn",
    "th": "thôi",
    "un": "uống",
    "xog": "xong",
    "ze": "ve",
    "zu": "du",
    "zo": "vô",
    "ziet": "viet",
    "zoi": "với",
    "zi": "gì",
    "z": "vậy",
    "zui": "vui",
    "zay": "vậy",
    "zua": "vua",
}